### ISSUE TITLE
How to set disablePushState = true

### ISSUE THREAD

**Issue by quorak** [zsajjad/react-facebook-pixel#11]
hey there, thanks a lot for the plugin,

what is the recommended approach to set ` disablePushState = true` as defined here: https://developers.facebook.com/ads/blog/post/2017/05/29/tagging-a-single-page-application-facebook-pixel/ ?

**Comment by frossi85** [comment]
@quorak that page do not recommend that. In one part of the articule he put:

```
fbq.disablePushState = true; //not recommended, but can be done
```

Also I would not trust too much in that article, is not well written and is super basic.

**Comment by annewanghy** [comment]
hello, I test in my environment ie, it doesn't solve the problem, still throw error when use event.preventDefault().
I check the fbq object, it is undefined
