### ISSUE TITLE
Why "React"?

### ISSUE THREAD

**Issue by Grsmto** [zsajjad/react-facebook-pixel#12]
Hi,
Thanks for the lib, I'm using it and it's cool. But why is there "react" in the name? From what I see in the code there is nothing related to React in this library, it's plain vanilla JS.

**Comment by zsajjad** [comment]
Any suggestions for the better name?

**Comment by Grsmto** [comment]
Maybe Facebook Pixel Helper. 
I guess the word "react" is driving most of the SEO tho so you can keep it in the readme.
But right now it's pretty confusing.
