### ISSUE TITLE
ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by marcolino** [zsajjad/react-facebook-pixel#19]
I did use react-facebook-pixel to log my react-native app purchase events to Facebook Pixel.  
When I run the app, I get the error in title, both in production and debug mode.  
I think the problem is due to the fact there is no DOM in a react app, and so no document...
But the `ReactPixel.init()` function uses it... :-(
Any suggestion ?

**Comment by zsajjad** [comment]
Same as #16
