### ISSUE TITLE
THIS MODULE DOES NOT WORK WITH REACT-NATIVE

### ISSUE THREAD

**Issue by marcolino** [zsajjad/react-facebook-pixel#20]
In *react-native* we don't have a `document`, since there is no `HTML DOM`...  
We have a `React virtual DOM`.

I understand the name should be clear (it is `react-facebook-pixel`, and not `react-native-facebook-pixel`...), but I write this issue just to warn react-native people to try using this module, since I lost quite a long time trying to debug it on react-native... :-(

**Comment by zsajjad** [comment]
Same as #16
