### ISSUE TITLE
Unable to delete pixel code

### ISSUE THREAD

**Issue by mihai93** [zsajjad/react-facebook-pixel#26]
Basically I have different pages with different pixel IDs and I need to clear the old code before initializing the new one (otherwise events would trigger for multiple IDs). I've tried to clear the window.fbq property by setting it to null or undefined, however that doesn't work and I just get this error:
`Multiple pixels with conflicting versions were detected on this page.`

Is it possible to clear all codes and re-initialize with a new one?

Thanks!

**Comment by mattgenious** [comment]
The two open pull requests add functionality that allow you to track on multiple initialized  pixels simultaneously effectively solving your problem.

**Comment by zsajjad** [comment]
Merged #24
