### ISSUE TITLE
pixel not working

### ISSUE THREAD

**Issue by theweiweiway** [zsajjad/react-facebook-pixel#28]
Hi, this is a very n00b issue but I am using this library with the Facebook Pixel Helper chrome extension and it is not detecting any pixels

Am I setting everything up right?
My App.js looks like this:

`
import ReactPixel from 'react-facebook-pixel';
`
`
  componentDidMount() {
`
`
    ReactPixel.init('my_id_here', {}, { autoConfig: false })
`
`
    ReactPixel.pageView();
`
`
  }
`

Is there something glaring I am doing wrong? I can't figure it out.
Thanks

**Comment by italobarbagelata** [comment]
Hello, 

not work for me

import ReactPixel from 'react-facebook-pixel'; 

default export is not declared in imported module import

version 0.1.3

plis!

**Comment by italobarbagelata** [comment]
Clean to npm

Edit version to "react-facebook-pixel": "0.1.1"

and install

working for me!

**Comment by theweiweiway** [comment]
sorry im an idiot. my adblocker was on
