### ISSUE TITLE
Push New Version to NPM

### ISSUE THREAD

**Issue by jovincroninwilesmith** [zsajjad/react-facebook-pixel#40]
The current version on NPM is lacking `fbq()`

**Comment by silveur** [comment]
Also 

> react_facebook_pixel__WEBPACK_IMPORTED_MODULE_1___default.a.trackSingle is not a function

I think the latest version wasn't pushed to npm

**Comment by hagmic** [comment]
The current version is also missing `revokeConsent()` and `grantConsent()`. Can we get the latest version of `master` published to NPM?

**Comment by muhmushtaha** [comment]
Any updates? @zsajjad

**Comment by zsajjad** [comment]
Released
