### ISSUE TITLE
Module not found: Can't resolve 'react-facebook-pixel' in '/Users/XXX/Projects/XXX/src'

### ISSUE THREAD

**Issue by blueandhack** [zsajjad/react-facebook-pixel#51]
When I upgrade react-facebook-pixel to 1.0 in my React project and try to run it, I face the problem.

**Comment by zsajjad** [comment]
Please try using [@zsajjad/react-facebook-pixel@1.0.1](https://github.com/zsajjad/react-facebook-pixel/packages/301420)

**Comment by pemasat** [comment]
I have same trouble. 
```npm install --save @zsajjad/react-facebook-pixel@1.0.1```
not helped.

**Comment by zsajjad** [comment]
Please make sure you're importing from same project.

```
import ReactPixel from '@zsajjad/react-facebook-pixel';
```

**Comment by pemasat** [comment]
I tried 
```
# npm install --save @zsajjad/react-facebook-pixel@1.0.1
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@zsajjad%2freact-facebook-pixel - Not found
npm ERR! 404 
npm ERR! 404  '@zsajjad/react-facebook-pixel@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
it not sound good : (
And if i check official released version https://github.com/zsajjad/react-facebook-pixel/releases there is maximum 1.0.0, not 1.0.1.

After this I tried ```npm install --save @zsajjad/react-facebook-pixel``` and same result. Only one what I can install is ```npm install --save react-facebook-pixel``` but in this case no one of variants
```import ReactPixel from '@zsajjad/react-facebook-pixel';```
or
```import ReactPixel from 'react-facebook-pixel';```
not work : (

**Comment by LuizHAP** [comment]
I got the above same error

**Comment by PhlipPhlops** [comment]
Same issue here

**Comment by zsajjad** [comment]
Unable to reproduce at my end, I wish if anyone can share demo repo.

**Comment by pemasat** [comment]
It saw that trouble is in npm repository. If I used yarn with react create aplication, it work.
```
# npx create-react-app player
# cd player/
# yarn add @zsajjad/react-facebook-pixel // failed
# yarn add react-facebook-pixel // ok, installed it version 1.0.3
# yarn start
```
in App I used ```import ReactPixel from 'react-facebook-pixel';```

**Comment by blueandhack** [comment]
I tried the new version 1.0.3, no problem with the new version.

**Comment by blueandhack** [comment]
BTW, I think you misunderstanding "NPM package registry" and" Github package registry"
When using the "Github package registry", `npm install --save @zsajjad/react-facebook-pixel` it may work, but for most users using the "NPM package registry," it does not work.

**Comment by zsajjad** [comment]
Yes i got that now. Apologies for inconvenience caused.

**Comment by pemasat** [comment]
Thank a lot for fixed. I confired that it work.

**Comment by PhlipPhlops** [comment]
Confirmed it's fix, thanks :)
